import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";

// Only include Kanit
const kanit = Kanit({
  subsets: ["latin"],
  weight: [ "700"],
  display:"swap"
});

export const metadata: Metadata = {
  title: "DELHI REDZ",
  description: "Generated by DELHI REDZ",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${kanit.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
